FROM --platform=linux/amd64 public.ecr.aws/docker/library/node:22-slim AS runner

# Lambda Web Adapterをコピー
COPY --from=public.ecr.aws/awsguru/aws-lambda-adapter:0.9.1-x86_64 /lambda-adapter /opt/extensions/lambda-adapter

# 環境変数設定
ENV PORT=3000 NODE_ENV=production AWS_LWA_INVOKE_MODE=buffered

WORKDIR /app

# 必要なファイルのみをコピー
COPY public ./public
COPY package.json ./package.json

# ⚠️ 重要: EC2でビルドした.nextフォルダを直接コピー
COPY .next/standalone ./
COPY .next/static ./.next/static

# run.shをコピー
COPY run.sh ./run.sh
RUN ln -s /tmp/cache ./.next/cache
RUN chmod +x ./run.sh

CMD exec ./run.sh
