FROM --platform=linux/amd64 public.ecr.aws/docker/library/node:22-slim AS runner
COPY --from=public.ecr.aws/awsguru/aws-lambda-adapter:0.9.1-x86_64 /lambda-adapter /opt/extensions/lambda-adapter

ENV PORT=3000 
ENV NODE_ENV=production 
ENV AWS_LWA_ENABLE_COMPRESSION=true
ENV HOSTNAME=0.0.0.0

WORKDIR /app

# EC2でビルド済みの成果物を直接コピー
COPY .next/standalone ./
COPY .next/static ./.next/static
COPY public ./public
COPY package.json ./package.json
COPY next.config.js ./next.config.js
COPY messages ./messages
COPY run.sh ./run.sh
COPY i18n.ts ./i18n.ts
COPY src ./src

RUN ln -s /tmp/cache ./.next/cache
RUN chmod +x ./run.sh

EXPOSE 3000

CMD exec ./run.sh
